services:
    alexdw_trumbowyg.form.type:
        class: "%alexdw_trumbowyg.form.type.class%"
        arguments: ["%alexdw_trumbowyg.config%"]
        tags:
          - { name: form.type }
    alexdw_trumbowyg.twig_extension:
            class: Alexdw\TrumbowygBundle\Twig\TrumbowygExtension
            public: false
            autowire: true
            tags:
                - { name: twig.extension }
